language: c

compiler: gcc

before_install:
        - sudo apt-get -qq update

script:
- "./bootstrap.sh"
- "./configure --enable-gcov"
- "make"

after_success:
        - bash <(curl -s https://codecov.io/bash)
