language: c

compiler: gcc

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install libcunit1-dev

script:
- "./bootstrap.sh"
- "./configure --enable-gcov"
- "make check"

after_success:
        - bash <(curl -s https://codecov.io/bash)
