language: c

compiler: gcc

os:
  - linux
  - osx
 

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libcunit1-dev ; fi

script:
- "./bootstrap.sh"
- "./configure --enable-gcov"
- "make check"

after_success:
        - bash <(curl -s https://codecov.io/bash)
