name: bitwise
version: "v0.22"
summary: Terminal based bitwise calculator in curses
description: |
        Interactively manipulate bits.

confinement: strict

apps:
        bitwise:
                command: bitwise
parts:
        bitwise:
                plugin: autotools
                source: https://github.com/mellowcandle/bitwise/releases/download/v0.22/bitwise-v0.22.tar.gz
                build-packages:
                        - libncurses5-dev
                        - libreadline-dev

