name: bitwise
version: "0.11"
summary: Terminal based bitwise calculator in curses
description: |
        Interactively manipulate bits.

confinement: strict

apps:
        bitwise:
                command: bitwise
parts:
        bitwise:
                plugin: autotools
                source: https://github.com/mellowcandle/bitwise/releases/download/0.11/bitwise-0.11.tar.gz
                build-packages: [libncurses5-dev]

